### ISSUE TITLE
Display of incomplete hours in reports

### ISSUE THREAD

**Issue by tev-cc** [jub77/grafikon#3]
Hello, 

Thank you for this application. 

I have a question about the display of hours in intermediate stations in the "Circulation of engineers" report (I have'nt check other reports right now). Hours do not always appear, minutes do. It's confusing (for us who are used to having HHmm on each line) :). Can this be fixed?
![image](https://user-images.githubusercontent.com/57351894/68117654-3b352e00-fefe-11e9-9682-301c579aac32.png)

Bt the way, is it possible to help you set up a French translation?

Thanks,

**Comment by jub77** [comment]
Hello,
the train timetable is modelled after czech timetable which if the hour does not change, then in the next column/row does not contain the hour information. I wouldn't like to change the default behaviour, what I can do is to add option to switch the the hour information to always on if checked. The file

[tt_always_hours_option.zip](https://github.com/jub77/grafikon/files/3810520/tt_always_hours_option.zip)

contains packed library with output templates with the additional option for output for drivers to be able to switch on option _Always show hours_. Unzipped templates can be imported by _File > Import > Import and replace templates..._ . The option can be switched on by editing output (Outputs > Outputs... and then editing output).

Thanks for offering to help with the translation, I would appreciate it. Regarding the program, for that I would need to prepare package for translating, but for the translation of the generated outputs - it is already integrated in the program:

1. Go to _Diagram > Languages..._ and add french
2. Then in _Outputs > Output templates... _ when editing template (the icon with list and pencil) there is third tabs (_Localization texts_) where the is possible to update the translation.
3. Select french in _Outputs > Language for outputs_ to french if it is not the default system language.
4. Now it is possible to check the result

You can send me then the exported updated output templates in gtml, or the gtm file itself would be enough. I could then include it in the default templates distributed with the program.

**Comment by tev-cc** [comment]
Hello,

Thank you for the checkbox for hours, it's very useful.

I have started translating the reports, but I have friends proofread them in order to propose the most relevant translation.

As soon as I get the feedback from everyone, I'll do an export.
