### ISSUE TITLE
MacOS theme doesn't work with dark theme

### ISSUE THREAD

**Issue by kudlav** [jub77/grafikon#4]
When Look and Feel is set to System or Mac OS X when using Mac OS system in Dark Mode, text is not displayed properly:
![Snímek obrazovky 2020-12-26 v 20 53 48](https://user-images.githubusercontent.com/11516259/103158322-c33e5d00-47bc-11eb-84bc-e9748745c85d.png)

Workaround is setting Look and Feel to Metal.

Mac OS Big Sur 11.1 (20C69)

**Comment by jub77** [comment]
Unfortunately it is not something which should be fixed in program, because the basic UI components are from Java standard library and the program is not modifiyng the default L&F of these components.

**Comment by jub77** [comment]
Fixed by newer jdk versions (14).
