### ISSUE TITLE
Dvojkolajna trat

### ISSUE THREAD

**Issue by Zugfanatiker** [jub77/grafikon#5]
Zdravim! Kamarat (poliak) pracuje na jednej trati do Grafikonu, je 2 kolajna, kolaje su spojene, vsetky vyzera byt v poriadku ALE appka nechce generovat jazdu vlaku cez kolaj 2, stale iba cez kolaj 1. Aj napriek tomu ze sa v tratovom useku nachadzaju 2 kolaje a stanice ich maju spojene. Mas tu na to nejaku radu?

Taktiez by som sa chcel opytat, ako sa generuje takyto zositovy cestovny poriadok ako tento tu https://github.com/jub77/grafikon/issues/3 

Dakujem za poradenie, pozdravujem!

**Comment by Zugfanatiker** [comment]
Dakujem za radu ohladom #3, fungovalo.

Ohladom tej dvojkolajnej trate mame stale problemy. Kamarat my poslal scenar, je v prilohe. Problem je, ze ked zo stanice Zychlin ide parny vlak po druhej tratovej kolaji do stanice Lowicz Glowny, nieje mozne, aj napriek tomu ze tratova kolaj 2 je spojena z kazdou kolajov stanice Lowicz Glowny, nastavit nastupistie ine ako 1. Skusali sme to opravit tak aj tak, na nic sme neprisli. Nemas tu na to nejake riesenie? 

Na schemate na Lowicz nachdza uplne vpravo, ide tam trasa cislo 03.

Pozdravujem a dakujem za pomoc!


[LKA.zip](https://github.com/jub77/grafikon/files/5824313/LKA.zip)

**Comment by jub77** [comment]
Problem je ze pres vice hran a uzlu jsou dve varianty a v soucasne dobe neni mozne editovat vice pozic naraz - takze jak jednou pri vytvareni se automaticky vybere prujezd pred Lowicz Glowny pres kolej 1 a nasledujici stanice ma tez pouze jednu spojovaci kolej. Tak uz nejde zmenit (kontrola navaznosti to nedovoli). Moznosti jak preci jenom vytvorit vlak ktery vyuzije jine spojeni, je vytvorit vlak ktery v Lowicz Glowny konci a upravit stanicni kolej. Protoze vlak ve stanici konci, tak to neni problem. Po uprave stanicni koleje (napr na 10), pak vyuzit moznosti upravit trasu vlak a prodlouzit ho. Pri prodlouzeni pak vypocet vyuzije jine spojeni z koleje 10 do nasledujici stanice (uprava trasy je v pod tlacitkem si ikonou klice).

**Comment by Zugfanatiker** [comment]
Ok, skusime to takto, dakujem velmi pekne!

**Comment by Zugfanatiker** [comment]
Zdravim, mam este jednu (a dufam ze poslednu) otazku.

Ked generujem vystup "Nákresne jizdni rády" resp. tie spojene, pise my to chybu. Pri generacii spojenych, my to generuje vsetko samostatne, a je to uplne necitatelne. Samostatne generovanie pada po 2 tratiach (2, prazdne, generuje uplne v poriadku). Verzia programu 3.1.0, sablony a vystupy su importovane z webu.

Nevies ako by sa to dalo poriesit? Treba pri tych vystupoch nieco vo velkom nastavovat? 

![image](https://user-images.githubusercontent.com/69450993/104826329-1904a300-5859-11eb-89a3-cb27e27207e2.png) < Vystup "vsetky trasy spojene", dalo mi to x samostatnych suborov, kazda trat zvlast, vyzera to takto.

![image](https://user-images.githubusercontent.com/69450993/104826765-36d20800-5859-11eb-81bf-1cd2b8476496.png) < All by one, dalo mi to iba 2, ostatok pada.

Subor dokladam : [SBL-game.zip](https://github.com/jub77/grafikon/files/5825268/SBL-game.zip)

**Comment by jub77** [comment]
Netestoval jsem graficky vystup s nastavenim kde jsou vzdalenosti v km... A to druhe je problem v nazvu ktery program automaticky vytvari. Oboji se bude muset opravit. V prilozenem zip souboru je rychla oprava tech sablon.

[SBL-game-fix.zip](https://github.com/jub77/grafikon/files/5825887/SBL-game-fix.zip)

**Comment by Zugfanatiker** [comment]
Existuje moznost, aby vystup nezaberal miesto pre objekt "navestidlo na sirej trati"? Potom by to generovalo asi krajsie. Pretoze jednokolajne trate, kde mas iba stanice a zastavky to generuje pekne, ale 2-kolajne trate kde je autoblok nechava vystup neskutocne odstopy pretoze drzi miesto pre navko. 

Taktiez ten title, ak by tam nebol objekt "navestidlo na sirej trati", velmi by mi to pomohlo. Ak to je vela roboty, nechaj tak, ale ak mas moznost, bol by som strasne rad ak by sa to dalo zmenit.

Velmi dakujem za pomoc a trpezlivost!

**Comment by jub77** [comment]
Oba dva vystupy nakresneho jizdniho radu potrebuje jistou korekci funkcnosti. Snad se k tomu v dohledne dobe dostanu.
