### ISSUE TITLE
How to print timetable in 4.0.0 version

### ISSUE THREAD

**Issue by lukaszun** [jub77/grafikon#6]
As in the title. I have no idea how to print created timetable.

**Comment by jub77** [comment]
There is no direct print from the program. You have to generate output files (html and/or pdf) and print it from appropriate programs.

Update (or insert if they are not present) templates - in menu _File > Import > Import and replace templates (web)_. It will put current output templates into timetable. Then the outputs then can be generated - from menu _Outputs > Outputs ..._ and _Generate all_ button (select the output location first).
