### ISSUE TITLE
[RFE]: Make current engineer's shift more visible in timetable

### ISSUE THREAD

**Issue by prcek-prcek** [jub77/grafikon#7]
I know every timetable already contains an information where and when an engineer drives the train.
I think - in the case an engineer doesn't drive the train the whole way - it would be helpful to have (optionally?) it visually marked in timetable itself. 
I would like to have a gray background for lines the engineer is not interested in.

Background: I've just came back from a meeting where someone run away with my train or demanded it too soon or panicked the train in specific timetable is already delayed.

I like this software and it helps me anyway.

--- czech version ---
Vím, že sešiťák obsahuje informace kdy a kde strojvedoucí přebírá / předává vlak, pokud ho nevede v celé trase.
Ovšem to je uvedeno pouze v tabulce v sešiťáku, ale ne v samotném jízdním řádu.
Myslím, že by bylo užitečné mít opticky označenou část jízdního řádu, která se na strojvedoucího nevztahuje, třeba šedým pozadím.

Pozadí: Právě jsem se vrátil ze setkání, kde mi někdo ujel s vlakem, který mi měl předat, nebo se ho dožadoval dřív, nebo panikařil, že vlak je zpožděný už ve chvíli, kdy si bere sešiťák.

Program je fajn, a rozhodně je pro nás užitečný.

**Comment by jub77** [comment]
There is new switch in the output - Highlight instead of limit, which should set background of not covered stations to light gray. The limit switch has to be switched on also.

It is available in templates on web.

**Comment by prcek-prcek** [comment]
Thank you very much!
